---
title: "Vignette"
output:
  html_document:
    theme: united
    toc: yes
vignette: |
  %\VignetteIndexEntry{Vignette} 
  %\VignetteEngine{knitr::rmarkdown} 
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}

#Clean workspace and memory ----
rm(list=ls())
gc()

#Set working directory ----
gps0=getwd()
gps0=paste(gps0,"/%s",sep="")
rootDir=gps0
setwd(gsub("%s","",rootDir))

#Load libraries ----
suppressWarnings(suppressMessages(
  library("Esearch3D", quietly = T)
  )
)

#Set variables ----
#Set seed to get always the same results out of this vignette
set.seed(8)
#Set number of cores to parallelize the tasks
n_cores=5
```

```{r example data loading}

#Load and set up the example data ----
data("dummy_data_l")
#gene - fragment interaction network
gf_net=dummy_data_l$gf_net
#gene-fragment-fragment interaction network
ff_net=dummy_data_l$ff_net
#sample profile with starting values for genes and fragments
input_m=dummy_data_l$input_m
#length of chromosomes
chr_len=dummy_data_l$chr_len
#gene annotation
ann_net_b=dummy_data_l$ann_net_b
```

```{r two step propagation with random walk with restart}

#Two step propagation -----
#Propagation over the gene-fragment network
gf_prop=rwr_OVprop(g=gf_net,input_m = input_m, no_cores=n_cores, r=0.1)
#Propagation over the gene-fragment-fragment network
ff_prop=rwr_OVprop(g=ff_net,input_m = gf_prop, no_cores=n_cores, r=0.8)

#Create igraph object with all the information included
net=create_net2plot(gf_net,input_m,gf_prop,ann_net_b,frag_pattern="F",ff_net,ff_prop)

#Start GUI
start_GUI(net, ann_net_b, chr_len, example=T)
```

```{r single gene propagation to infer information about seed and target nodes }

#Single gene propagation -----
degree = 3
frag_pattern = "F"
gene_in=c("G1")

contrXgene_l=rwr_SGprop(gf_net, ff_net, gene_in, frag_pattern,
                        degree = degree, r1 = 0.1, r2 = 0.8, no_cores = n_cores)

#Create igraph object with all the information included
sff_prop=as.matrix(contrXgene_l$G1$contr_lxDest$ff_prop[,gene_in])
colnames(sff_prop)=gene_in
#Create igraph object with all the information included
net=create_net2plot(gf_net,input_m,gf_prop,ann_net_b,frag_pattern="F",ff_net,ff_prop)

#Start GUI
start_GUI(net, ann_net_b, chr_len, example=T)
```











